services:
  literaturaDB:
    image: postgres:15.3
    container_name: my-literaturaDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=alumno
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=literatura-db
    volumes:
      - ./postgres:/var/lib/postgresql/data